name: E2E test

on:
  push:
    branches: [trunk]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [trunk]
  schedule:
    - cron: '36 7 * * 6'

jobs:
  changed-files:
    name: Changed Files
    outputs:
      status: ${{ steps.changed-files.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            .github/*
            src/*
            tests/*
            cypress-wp-utils.php
            .wp-env.json
            package.json
            package-lock.json
      - name: List Modified Files
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs ls -lh

  cypress:
    name: ${{ matrix.core.name }}
    needs: changed-files
    if: ${{ needs.changed-files.outputs.status == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core:
          - { name: 'WP latest', version: 'latest' }
          - { name: 'WP trunk', version: 'WordPress/WordPress#master' }
          - { name: 'WP minimum', version: 'WordPress/WordPress#5.2' }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        continue-on-error: true
      - name: Set the core version
        run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}
      - name: Set up WP environment
        run: npm run env:start
      - name: Test
        run: npm run cypress:run
      - name: Make artifacts available
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifact
          retention-days: 2
          path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
