name: Update built branch

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create the build folder
        run: |
          mkdir build
          cp package.json build/
          mv lib build/

      - name: Push
        uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98 # develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
